name: Test Runner

on:
  push:
    branches: [feat/self-hosted-runners]
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - run: echo "Hello from self-hosted runner!"
      - run: node -v
      - run: npm -v
